#ifndef GUARD_CONFIG_SONGS_ENABLED_H
#define GUARD_CONFIG_SONGS_ENABLED_H

// These tracks currently have no references in game code, maps, or scripts.
// Set an individual value to 1 before using that MUS_* constant again.
// The build-time song configuration check enforces this automatically.

// Diamond / Pearl
#define SONG_MUS_DP_TWINLEAF_DAY                        0
#define SONG_MUS_DP_SANDGEM_DAY                         0
#define SONG_MUS_DP_SOLACEON_DAY                        0
#define SONG_MUS_DP_VALOR_LAKEFRONT_DAY                 0
#define SONG_MUS_DP_JUBILIFE_DAY                        0
#define SONG_MUS_DP_CANALAVE_DAY                        0
#define SONG_MUS_DP_OREBURGH_DAY                        0
#define SONG_MUS_DP_ETERNA_DAY                          0
#define SONG_MUS_DP_HEARTHOME_DAY                       0
#define SONG_MUS_DP_SNOWPOINT_DAY                       0
#define SONG_MUS_DP_POKEMON_LEAGUE_DAY                  0
#define SONG_MUS_DP_FIGHT_AREA_DAY                      0
#define SONG_MUS_DP_ROUTE201_DAY                        0
#define SONG_MUS_DP_ROUTE203_DAY                        0
#define SONG_MUS_DP_ROUTE205_DAY                        0
#define SONG_MUS_DP_ROUTE206_DAY                        0
#define SONG_MUS_DP_ROUTE216_DAY                        1
#define SONG_MUS_DP_ROUTE228_DAY                        0
#define SONG_MUS_DP_ROWAN                               0
#define SONG_MUS_DP_TV_BROADCAST                        0
#define SONG_MUS_DP_TWINLEAF_NIGHT                      0
#define SONG_MUS_DP_SANDGEM_NIGHT                       0
#define SONG_MUS_DP_SOLACEON_NIGHT                      0
#define SONG_MUS_DP_ROUTE225_NIGHT                      0
#define SONG_MUS_DP_VALOR_LAKEFRONT_NIGHT               0
#define SONG_MUS_DP_JUBILIFE_NIGHT                      0
#define SONG_MUS_DP_CANALAVE_NIGHT                      0
#define SONG_MUS_DP_OREBURGH_NIGHT                      0
#define SONG_MUS_DP_ETERNA_NIGHT                        0
#define SONG_MUS_DP_VEILSTONE_NIGHT                     0
#define SONG_MUS_DP_SUNYSHORE_NIGHT                     0
#define SONG_MUS_DP_POKEMON_LEAGUE_NIGHT                0
#define SONG_MUS_DP_FIGHT_AREA_NIGHT                    0
#define SONG_MUS_DP_ROUTE206_NIGHT                      0
#define SONG_MUS_DP_ROUTE209_NIGHT                      0
#define SONG_MUS_DP_ROUTE210_NIGHT                      0
#define SONG_MUS_DP_ROUTE216_NIGHT                      1
#define SONG_MUS_DP_UNDERGROUND                         0
#define SONG_MUS_DP_FLAG_CAPTURED                       0
#define SONG_MUS_DP_VICTORY_ROAD                        0
#define SONG_MUS_DP_OLD_CHATEAU                         0
#define SONG_MUS_DP_AMITY_SQUARE                        0
#define SONG_MUS_DP_GALACTIC_HQ                         0
#define SONG_MUS_DP_GALACTIC_ETERNA_BUILDING            0
#define SONG_MUS_DP_LAKE                                1
#define SONG_MUS_DP_SPEAR_PILLAR                        1
#define SONG_MUS_DP_STARK_MOUNTAIN                      1
#define SONG_MUS_DP_OREBURGH_GATE                       0
#define SONG_MUS_DP_INSIDE_POKEMON_LEAGUE               0
#define SONG_MUS_DP_HALL_OF_FAME_ROOM                   0
#define SONG_MUS_DP_POKE_CENTER_DAY                     0
#define SONG_MUS_DP_POKE_CENTER_NIGHT                   1
#define SONG_MUS_DP_GYM                                 0
#define SONG_MUS_DP_ROWAN_LAB                           0
#define SONG_MUS_DP_CONTEST_LOBBY                       0
#define SONG_MUS_DP_POKE_MART                           0
#define SONG_MUS_DP_GAME_CORNER                         0
#define SONG_MUS_DP_TV_STATION                          0
#define SONG_MUS_DP_GALACTIC_HQ_BASEMENT                0
#define SONG_MUS_DP_AZURE_FLUTE                         0
#define SONG_MUS_DP_HALL_OF_ORIGIN                      0
#define SONG_MUS_DP_GTS                                 0
#define SONG_MUS_DP_VS_WILD                             0
#define SONG_MUS_DP_VS_GALACTIC_BOSS                    0
#define SONG_MUS_DP_VS_DIALGA_PALKIA                    1
#define SONG_MUS_DP_VS_GALACTIC                         0
#define SONG_MUS_DP_VS_RIVAL                            0
#define SONG_MUS_DP_VS_ARCEUS                           0
#define SONG_MUS_DP_VICTORY_WILD                        0
#define SONG_MUS_DP_VICTORY_TRAINER                     0
#define SONG_MUS_DP_VICTORY_GYM_LEADER                  0
#define SONG_MUS_DP_VICTORY_CHAMPION                    0
#define SONG_MUS_DP_VICTORY_GALACTIC                    0
#define SONG_MUS_DP_VICTORY_ELITE_FOUR                  0
#define SONG_MUS_DP_VS_GALACTIC_COMMANDER               0
#define SONG_MUS_DP_CONTEST                             0
#define SONG_MUS_DP_VS_ELITE_FOUR                       0
#define SONG_MUS_DP_FOLLOW_ME                           0
#define SONG_MUS_DP_RIVAL                               0
#define SONG_MUS_DP_LAKE_EVENT                          0
#define SONG_MUS_DP_EVOLUTION                           0
#define SONG_MUS_DP_LUCAS                               0
#define SONG_MUS_DP_DAWN                                0
#define SONG_MUS_DP_LEGEND_APPEARS                      0
#define SONG_MUS_DP_CATASTROPHE                         0
#define SONG_MUS_DP_POKE_RADAR                          0
#define SONG_MUS_DP_SURF                                0
#define SONG_MUS_DP_CYCLING                             0
#define SONG_MUS_DP_LETS_GO_TOGETHER                    0
#define SONG_MUS_DP_TV_END                              0
#define SONG_MUS_DP_LEVEL_UP                            0
#define SONG_MUS_DP_EVOLVED                             0
#define SONG_MUS_DP_OBTAIN_KEY_ITEM                     0
#define SONG_MUS_DP_OBTAIN_ITEM                         0
#define SONG_MUS_DP_CAUGHT_INTRO                        0
#define SONG_MUS_DP_DEX_RATING                          0
#define SONG_MUS_DP_OBTAIN_BADGE                        0
#define SONG_MUS_DP_POKETCH                             0
#define SONG_MUS_DP_OBTAIN_TMHM                         0
#define SONG_MUS_DP_OBTAIN_ACCESSORY                    0
#define SONG_MUS_DP_MOVE_DELETED                        0
#define SONG_MUS_DP_HEAL                                0
#define SONG_MUS_DP_OBTAIN_BERRY                        0
#define SONG_MUS_DP_CONTEST_DRESS_UP                    0
#define SONG_MUS_DP_HALL_OF_FAME                        0
#define SONG_MUS_DP_INTRO                               0
#define SONG_MUS_DP_TITLE                               0
#define SONG_MUS_DP_MYSTERY_GIFT                        0
#define SONG_MUS_DP_WFC                                 0
#define SONG_MUS_DP_DANCE_EASY                          0
#define SONG_MUS_DP_DANCE_DIFFICULT                     0
#define SONG_MUS_DP_CONTEST_RESULTS                     0
#define SONG_MUS_DP_CONTEST_WINNER                      0
#define SONG_MUS_DP_POFFINS                             0
#define SONG_MUS_DP_SLOTS_WIN                           0
#define SONG_MUS_DP_SLOTS_JACKPOT                       0
#define SONG_MUS_DP_CREDITS                             0
#define SONG_MUS_DP_SLOTS_UNUSED                        0

// Platinum
#define SONG_MUS_PL_FIGHT_AREA_DAY                      0
#define SONG_MUS_PL_TV_BROADCAST                        0
#define SONG_MUS_PL_TV_END                              0
#define SONG_MUS_PL_INTRO                               0
#define SONG_MUS_PL_TITLE                               0
#define SONG_MUS_PL_DISTORTION_WORLD                    0
#define SONG_MUS_PL_B_ARCADE                            0
#define SONG_MUS_PL_B_HALL                              0
#define SONG_MUS_PL_B_CASTLE                            0
#define SONG_MUS_PL_B_FACTORY                           0
#define SONG_MUS_PL_GLOBAL_TERMINAL                     0
#define SONG_MUS_PL_LILYCOVE_BOSSA_NOVA                 0
#define SONG_MUS_PL_LOOKER                              0
#define SONG_MUS_PL_VS_GIRATINA                         0
#define SONG_MUS_PL_VS_FRONTIER_BRAIN                   0
#define SONG_MUS_PL_VICTORY_FRONTIER_BRAIN              0
#define SONG_MUS_PL_VS_REGI                             0
#define SONG_MUS_PL_CONTEST_COOL                        0
#define SONG_MUS_PL_CONTEST_SMART                       0
#define SONG_MUS_PL_CONTEST_CUTE                        0
#define SONG_MUS_PL_CONTEST_TOUGH                       0
#define SONG_MUS_PL_CONTEST_BEAUTY                      0
#define SONG_MUS_PL_SPIN_TRADE                          0
#define SONG_MUS_PL_WIFI_MINIGAMES                      0
#define SONG_MUS_PL_WIFI_PLAZA                          0
#define SONG_MUS_PL_WIFI_PARADE                         0
#define SONG_MUS_PL_GIRATINA_APPEARS_1                  0
#define SONG_MUS_PL_GIRATINA_APPEARS_2                  0
#define SONG_MUS_PL_MYSTERY_GIFT                        0
#define SONG_MUS_PL_TWINLEAF_MUSIC_BOX                  0
#define SONG_MUS_PL_OBTAIN_ARCADE_POINTS                0
#define SONG_MUS_PL_OBTAIN_CASTLE_POINTS                0
#define SONG_MUS_PL_OBTAIN_B_POINTS                     0
#define SONG_MUS_PL_WIN_MINIGAME                        0

// HeartGold / SoulSilver
#define SONG_MUS_HG_INTRO                               0
#define SONG_MUS_HG_EVOLUTION                           0
#define SONG_MUS_HG_EVOLUTION_NO_INTRO                  1
#define SONG_MUS_HG_CYCLING                             0
#define SONG_MUS_HG_HALL_OF_FAME                        0
#define SONG_MUS_HG_CREDITS                             0
#define SONG_MUS_HG_END                                 0
#define SONG_MUS_HG_B_TOWER                             0
#define SONG_MUS_HG_B_TOWER_RECEPTION                   0
#define SONG_MUS_HG_FOLLOW_ME_2                         0
#define SONG_MUS_HG_BUG_CONTEST_PREP                    0
#define SONG_MUS_HG_BUG_CATCHING_CONTEST                0
#define SONG_MUS_HG_MAGNET_TRAIN                        0
#define SONG_MUS_HG_RADIO_JINGLE                        0
#define SONG_MUS_HG_CLAIR                               0
#define SONG_MUS_HG_VS_WILD_KANTO                       0
#define SONG_MUS_HG_VICTORY_TRAINER                     1
#define SONG_MUS_HG_VICTORY_WILD                        1
#define SONG_MUS_HG_CAUGHT                              1
#define SONG_MUS_HG_VICTORY_GYM_LEADER                  1
#define SONG_MUS_HG_POKEATHLON_LOBBY                    0
#define SONG_MUS_HG_POKEATHLON_START                    0
#define SONG_MUS_HG_POKEATHLON_BEFORE                   0
#define SONG_MUS_HG_POKEATHLON_EVENT                    0
#define SONG_MUS_HG_POKEATHLON_FINALS                   0
#define SONG_MUS_HG_POKEATHLON_RESULTS                  0
#define SONG_MUS_HG_POKEATHLON_END                      0
#define SONG_MUS_HG_POKEATHLON_WINNER                   0
#define SONG_MUS_HG_B_HALL                              0
#define SONG_MUS_HG_B_CASTLE                            0
#define SONG_MUS_HG_VICTORY_FRONTIER_BRAIN              0
#define SONG_MUS_HG_WFC                                 0
#define SONG_MUS_HG_MYSTERY_GIFT                        0
#define SONG_MUS_HG_WIFI_PLAZA                          0
#define SONG_MUS_HG_WIFI_MINIGAMES                      0
#define SONG_MUS_HG_WIFI_PARADE                         0
#define SONG_MUS_HG_GLOBAL_TERMINAL                     0
#define SONG_MUS_HG_SPIN_TRADE                          0
#define SONG_MUS_HG_GTS                                 0
#define SONG_MUS_HG_ETHAN                               0
#define SONG_MUS_HG_GAME_CORNER_WIN                     0
#define SONG_MUS_HG_HO_OH_APPEARS                       0
#define SONG_MUS_HG_LUGIA_APPEARS                       0
#define SONG_MUS_HG_SPIKY_EARED_PICHU                   0
#define SONG_MUS_HG_RADIO_ROUTE101                      1
#define SONG_MUS_HG_RADIO_ROUTE201                      0
#define SONG_MUS_HG_RADIO_TRAINER                       0
#define SONG_MUS_HG_RADIO_VARIETY                       0
#define SONG_MUS_HG_VS_KYOGRE_GROUDON                   1
#define SONG_MUS_HG_POKEWALKER                          0
#define SONG_MUS_HG_VS_ARCEUS                           0
#define SONG_MUS_HG_OBTAIN_ACCESSORY                    0
#define SONG_MUS_HG_DEX_RATING_1                        0
#define SONG_MUS_HG_DEX_RATING_2                        0
#define SONG_MUS_HG_DEX_RATING_3                        0
#define SONG_MUS_HG_DEX_RATING_4                        0
#define SONG_MUS_HG_DEX_RATING_5                        0
#define SONG_MUS_HG_DEX_RATING_6                        0
#define SONG_MUS_HG_OBTAIN_EGG                          0
#define SONG_MUS_HG_BUG_CONTEST_1ST_PLACE               0
#define SONG_MUS_HG_BUG_CONTEST_2ND_PLACE               0
#define SONG_MUS_HG_BUG_CONTEST_3RD_PLACE               0
#define SONG_MUS_HG_CARD_FLIP                           0
#define SONG_MUS_HG_CARD_FLIP_GAME_OVER                 0
#define SONG_MUS_HG_LETS_GO_TOGETHER                    0
#define SONG_MUS_HG_POKEATHLON_READY                    0
#define SONG_MUS_HG_POKEATHLON_1ST_PLACE                0
#define SONG_MUS_HG_RECEIVE_POKEMON                     0
#define SONG_MUS_HG_OBTAIN_ARCADE_POINTS                0
#define SONG_MUS_HG_OBTAIN_CASTLE_POINTS                0
#define SONG_MUS_HG_WIN_MINIGAME                        0

#endif // GUARD_CONFIG_SONGS_ENABLED_H
